### ISSUE TITLE
google-services.json file is missing

### ISSUE THREAD

**Issue by firoz3130** [PEC-CSS/Time-Table-App#14]
Need help in this
* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location:

**Comment by notSanil** [comment]
Can you post a longer error message, I am not entirely sure why it's asking for this file in the current stage

**Comment by firoz3130** [comment]
This was the error message
Seems like a file is missing in it. Do i have to bring it separately?
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  D:\personal\Time-Table-App\android\app\src\debug\google-services.json
  D:\personal\Time-Table-App\android\app\src\google-services.json
  D:\personal\Time-Table-App\android\app\google-services.json


* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output

**Comment by notSanil** [comment]
Alright, I've found the problem
https://github.com/PEC-CSS/Time-Table-App/blob/f1efb03cf5f673cb839dacc8f81527bb7e9ebc01/android/app/build.gradle#L75
I accidentally committed this line, remove it, and it should run fine

**Comment by firoz3130** [comment]
ok 
now it's working fine

**Comment by notSanil** [comment]
Great, marking the issue as closed then.
